### ISSUE TITLE
Typing text animation 

### ISSUE THREAD

**Issue by Umar293** [thamesweb/HackToberFest2022#68]
Typing text animation using HTML, CSS and JS.
Please assign me this issue.

**Comment by Manishgupta200** [comment]
Hey. Recently i made a project where the typing text animation are in used. Please assign in to me @Umar293 under Hacktoberfest. I would like to work on it.

**Comment by thamesweb** [comment]
Hey @Manishgupta200, If you want to work on this issue just give a 👍 to this comment. I will assign it to you.

**Comment by Manishgupta200** [comment]
I solved this issue. Please look on it.
