### ISSUE TITLE
JS weather app

### ISSUE THREAD

**Issue by Muhammad-Anus-Developer** [thamesweb/HackToberFest2022#82]
Can I add my JS weather app? Please assign this to me.

**Comment by thamesweb** [comment]
@Muhammad-Anus-Developer Go Ahead.

**Comment by thamesweb** [comment]
@Muhammad-Anus-Developer are you working on it or I should close this issue?

**Comment by Muhammad-Anus-Developer** [comment]
Yeah I am working on it. Already finished with functionality. Just working on it's UI.

**Comment by Muhammad-Anus-Developer** [comment]
I have pushed the code. Please check
